//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuste
    {
        public int IDConfig { get; set; }
        public int IDPeriodoActual { get; set; }
    
        public virtual Periodo Periodo { get; set; }
    }
}
