//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloqueAcademicoXPlanDeEstudio
    {
        public BloqueAcademicoXPlanDeEstudio()
        {
            this.BloqueXPlanXCursoes = new HashSet<BloqueXPlanXCurso>();
        }
    
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int BloqueID { get; set; }
    
        public virtual BloqueAcademico BloqueAcademico { get; set; }
        public virtual PlanesDeEstudio PlanesDeEstudio { get; set; }
        public virtual ICollection<BloqueXPlanXCurso> BloqueXPlanXCursoes { get; set; }
    }
}
