//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloqueAcademico
    {
        public BloqueAcademico()
        {
            this.BloqueAcademicoXPlanDeEstudios = new HashSet<BloqueAcademicoXPlanDeEstudio>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int Nivel { get; set; }
    
        public virtual ICollection<BloqueAcademicoXPlanDeEstudio> BloqueAcademicoXPlanDeEstudios { get; set; }
    }
}
