//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Grupo
    {
        public int Id { get; set; }
        public int Grupo { get; set; }
        public int Profesor { get; set; }
        public int Horario { get; set; }
        public string Aula { get; set; }
        public Nullable<int> Cupo { get; set; }
    
        public virtual Horario Horario1 { get; set; }
        public virtual ProfesoresXCurso ProfesoresXCurso { get; set; }
    }
}
