//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia
    {
        public int Id { get; set; }
        public string Dia1 { get; set; }
        public int Horario { get; set; }
        public Nullable<int> Hora_Inicio { get; set; }
        public Nullable<int> Hora_Fin { get; set; }
    
        public virtual Horario Horario1 { get; set; }
    }
}
