//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public int ID { get; set; }
        public int Numero { get; set; }
        public int PlanDeEstudio { get; set; }
        public int Periodo { get; set; }
        public int BloqueXPlanXCursoID { get; set; }
    
        public virtual BloqueXPlanXCurso BloqueXPlanXCurso { get; set; }
        public virtual Periodo Periodo1 { get; set; }
        public virtual PlanesDeEstudioXSede PlanesDeEstudioXSede { get; set; }
    }
}
