//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.Ajustes = new HashSet<Ajuste>();
            this.ComisionesXProfesors = new HashSet<ComisionesXProfesor>();
            this.Grupoes = new HashSet<Grupo>();
            this.ProyectosXProfesors = new HashSet<ProyectosXProfesor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Ajuste> Ajustes { get; set; }
        public virtual ICollection<ComisionesXProfesor> ComisionesXProfesors { get; set; }
        public virtual ICollection<Grupo> Grupoes { get; set; }
        public virtual ICollection<ProyectosXProfesor> ProyectosXProfesors { get; set; }
    }
}
