//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesDeEstudioXSede
    {
        public PlanesDeEstudioXSede()
        {
            this.Grupoes = new HashSet<Grupo>();
        }
    
        public int ID { get; set; }
        public int Sede { get; set; }
        public int PlanDeEstudio { get; set; }
    
        public virtual ICollection<Grupo> Grupoes { get; set; }
        public virtual PlanesDeEstudio PlanesDeEstudio { get; set; }
        public virtual Sede Sede1 { get; set; }
    }
}
