//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public Plaza()
        {
            this.PlazaXProfesors = new HashSet<PlazaXProfesor>();
        }
    
        public int ID { get; set; }
        public string Codigo_Plaza { get; set; }
        public string Tipo_de_plaza { get; set; }
        public string Tipo_segun_tiempo { get; set; }
        public Nullable<int> Horas_Totales { get; set; }
        public Nullable<int> Tiempo_de_vigencia { get; set; }
    
        public virtual ICollection<PlazaXProfesor> PlazaXProfesors { get; set; }
    }
}
