//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.ProyectosXProfesors = new HashSet<ProyectosXProfesor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public int Estado { get; set; }
        public string Link { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<ProyectosXProfesor> ProyectosXProfesors { get; set; }
    }
}
