//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Aulas = new HashSet<Aula>();
            this.PlanesDeEstudioXSedes = new HashSet<PlanesDeEstudioXSede>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Aula> Aulas { get; set; }
        public virtual ICollection<PlanesDeEstudioXSede> PlanesDeEstudioXSedes { get; set; }
    }
}
