//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEntidad
    {
        public TipoEntidad()
        {
            this.Comisiones = new HashSet<Comisione>();
            this.PlanesDeEstudios = new HashSet<PlanesDeEstudio>();
            this.Proyectos = new HashSet<Proyecto>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Comisione> Comisiones { get; set; }
        public virtual ICollection<PlanesDeEstudio> PlanesDeEstudios { get; set; }
        public virtual ICollection<Proyecto> Proyectos { get; set; }
    }
}
